env:
  TERM: alacritty

#------------------------------------------------------------------------------#
#                                    Window                                    #
#------------------------------------------------------------------------------#
window:
  dimensions:
    columns: 100
    lines: 40

  position:
    x: 300
    y: 300

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed
  dynamic_title: true

scrolling:
  history: 1000
  multiplier: 3

#------------------------------------------------------------------------------#
#                                     Font                                     #
#------------------------------------------------------------------------------#
font:
  normal:
    family: CaskaydiaCove Nerd Font
    style: Regular

  bold:
    family: CaskaydiaCove Nerd Font
    style: Bold

  italic:
    family: CaskaydiaCove Nerd Font
    style: Regular Italic

  bold_italic:
    family: CaskaydiaCove Nerd Font
    style: Bold Italic
  size: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

#------------------------------------------------------------------------------#
#                                   One Dark                                   #
#------------------------------------------------------------------------------#
colors:
  # Default colors
  primary:
    background: "0x1e2127"
    foreground: "0xabb2bf"

  # Normal colors
  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"

#------------------------------------------------------------------------------#
#                                Window opacity                                #
#------------------------------------------------------------------------------#
background_opacity: 0.85

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: Off

#------------------------------------------------------------------------------#
#                                    Mouse                                     #
#------------------------------------------------------------------------------#
mouse:
  url:
    modifiers: Control
