[directory]
truncation_length = 5

[env_var.has_proxy]
style = "green bold"
default = "noproxy"

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[dart]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = " "

[git_commit]
tag_symbol = " "

[golang]
symbol = "go "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = "node"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "
